apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: techx-trainee-dev
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: registry.hub.docker.com/pttzx/nodeapp:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
       - name: regcred
        
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dev.properties
  namespace: techx-trainee-dev
data:
  NODE_PORT: 3000
  SERVER_NAME: nodeapp-dev
  DB_URL: rds-server-dev.com
  
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: nodeapp-service
# spec:
#   namespace: dev_namespace
#   type: NodePort
#   selector:
#     app: nodeapp 
#   ports:
#   - protocol: TCP
#     port: 3000
#     targetPort: 3000
#     nodePort: 31110